### ISSUE TITLE
installation issue (Ubuntu 18.04, SolarUtils 0.3)

### ISSUE THREAD

**Issue by jehyunlee** [SunPower/SolarUtils#19]
whether I try `pip install SolarUtils` or `python setup.py install` after `git clone`, I meet the following messages:

```
Collecting SolarUtils
  Using cached SolarUtils-0.3.tar.gz (357 kB)
    ERROR: Command errored out with exit status 1:
     command: /opt/conda/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-gdxv0oi8/solarutils/setup.py'"'"'; __file__='"'"'/tmp/pip-install-gdxv0oi8/solarutils/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-p6_ln8po
         cwd: /tmp/pip-install-gdxv0oi8/solarutils/
    Complete output (22 lines):
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.7/distutils/unixccompiler.py", line 118, in _compile
        extra_postargs)
      File "/opt/conda/lib/python3.7/distutils/ccompiler.py", line 909, in spawn
        spawn(cmd, dry_run=self.dry_run)
      File "/opt/conda/lib/python3.7/distutils/spawn.py", line 36, in spawn
        _spawn_posix(cmd, search_path, dry_run=dry_run)
      File "/opt/conda/lib/python3.7/distutils/spawn.py", line 159, in _spawn_posix
        % (cmd, exit_status))
    distutils.errors.DistutilsExecError: command 'cc' failed with exit status 1

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-gdxv0oi8/solarutils/setup.py", line 154, in <module>
        extra_preargs=CCFLAGS, macros=MACROS)
      File "/opt/conda/lib/python3.7/distutils/ccompiler.py", line 574, in compile
        self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
      File "/opt/conda/lib/python3.7/distutils/unixccompiler.py", line 120, in _compile
        raise CompileError(msg)
    distutils.errors.CompileError: command 'cc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

I've tried `pip install setuptools --upgrade` to version 50.3.0 and `pip install pip --upgrade` to version 20.2.3 in advance as well, but all the same.  
Is there any options I can try?

**Comment by mikofski** [comment]
Hi @jehyunlee,

Thanks for the report! Unfortunately, I cannot reproduce the error you're experiencing. I am using Ubuntu 20.04 on WSL with miniconda. Here are my steps:

_click **Details** to expand_

1. create a new python3.7 environment with setuptools & pip
<details>

```
~$ conda create -n py37 python=3.7 setuptools pip wheel
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.8.3
  latest version: 4.8.5

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /home/mikm/miniconda3/envs/py37

  added / updated specs:
    - pip
    - python=3.7
    - setuptools
    - wheel


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2020.7.22  |                0         125 KB
    certifi-2020.6.20          |           py37_0         156 KB
    libedit-3.1.20191231       |       h14c3975_1         116 KB
    libffi-3.3                 |       he6710b0_2          50 KB
    openssl-1.1.1h             |       h7b6447c_0         2.5 MB
    pip-20.2.3                 |           py37_0         1.7 MB
    python-3.7.9               |       h7579374_0        45.3 MB
    setuptools-50.3.0          |   py37hb0f4dca_1         710 KB
    sqlite-3.33.0              |       h62c20be_0         1.1 MB
    tk-8.6.10                  |       hbc83047_0         3.0 MB
    wheel-0.35.1               |             py_0          37 KB
    ------------------------------------------------------------
                                           Total:        54.9 MB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main
  ca-certificates    pkgs/main/linux-64::ca-certificates-2020.7.22-0
  certifi            pkgs/main/linux-64::certifi-2020.6.20-py37_0
  ld_impl_linux-64   pkgs/main/linux-64::ld_impl_linux-64-2.33.1-h53a641e_7
  libedit            pkgs/main/linux-64::libedit-3.1.20191231-h14c3975_1
  libffi             pkgs/main/linux-64::libffi-3.3-he6710b0_2
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-9.1.0-hdf63c60_0
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-9.1.0-hdf63c60_0
  ncurses            pkgs/main/linux-64::ncurses-6.2-he6710b0_1
  openssl            pkgs/main/linux-64::openssl-1.1.1h-h7b6447c_0
  pip                pkgs/main/linux-64::pip-20.2.3-py37_0
  python             pkgs/main/linux-64::python-3.7.9-h7579374_0
  readline           pkgs/main/linux-64::readline-8.0-h7b6447c_0
  setuptools         pkgs/main/linux-64::setuptools-50.3.0-py37hb0f4dca_1
  sqlite             pkgs/main/linux-64::sqlite-3.33.0-h62c20be_0
  tk                 pkgs/main/linux-64::tk-8.6.10-hbc83047_0
  wheel              pkgs/main/noarch::wheel-0.35.1-py_0
  xz                 pkgs/main/linux-64::xz-5.2.5-h7b6447c_0
  zlib               pkgs/main/linux-64::zlib-1.2.11-h7b6447c_3


Proceed ([y]/n)?


Downloading and Extracting Packages
python-3.7.9         | 45.3 MB   | ############################################################################# | 100%
openssl-1.1.1h       | 2.5 MB    | ############################################################################# | 100%
wheel-0.35.1         | 37 KB     | ############################################################################# | 100%
tk-8.6.10            | 3.0 MB    | ############################################################################# | 100%
certifi-2020.6.20    | 156 KB    | ############################################################################# | 100%
pip-20.2.3           | 1.7 MB    | ############################################################################# | 100%
libffi-3.3           | 50 KB     | ############################################################################# | 100%
libedit-3.1.20191231 | 116 KB    | ############################################################################# | 100%
ca-certificates-2020 | 125 KB    | ############################################################################# | 100%
sqlite-3.33.0        | 1.1 MB    | ############################################################################# | 100%
setuptools-50.3.0    | 710 KB    | ############################################################################# | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate py37
#
# To deactivate an active environment, use
#
#     $ conda deactivate
```

</details>

2. activate and install SolarUtils

<details>

```
~$ conda activate py37
(py37) ~$ pip install solarutils
Collecting solarutils
  Downloading SolarUtils-0.3.tar.gz (357 kB)
     |████████████████████████████████| 357 kB 711 kB/s
Building wheels for collected packages: solarutils
  Building wheel for solarutils (setup.py) ... done
  Created wheel for solarutils: filename=SolarUtils-0.3-cp37-cp37m-linux_x86_64.whl size=50494 sha256=3a2c75f32357de13e10f9658a657b7f37027a3d9c55cb87160a9a275abd45ceb
  Stored in directory: /home/mikm/.cache/pip/wheels/6d/84/f5/1284cfd9d778cf94091cfc0504c2890f949c3d1dbd415228ea
Successfully built solarutils
Installing collected packages: solarutils
Successfully installed solarutils-0.3
```

</details>

3. start python and run the example

<details>

```
(py37) ~$ python
Python 3.7.9 (default, Aug 31 2020, 12:42:55)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from solar_utils import *
>>> location = [35.56836, -119.2022, -8.0]
>>> datetime = [2013, 6, 5, 12, 31, 0]
>>> weather = [1015.62055, 40.0]
>>> (angles, airmass) = solposAM(location, datetime, weather)
>>> angles
<solar_utils.core.c_float_Array_2 object at 0x7fddbc80c9e0>
>>> angles[:]
[15.074043273925781, 213.29042053222656]
>>> airmass[:]
[1.0352272987365723, 1.0379053354263306]
>>>
```

</details>

Can you try again with my steps? Specifically install SolarUtils into a fresh, clean conda environment?

**Comment by mikofski** [comment]
Also if you are looking for a solar position algorithm, try [`pvlib.solarposition.get_solarposition`](https://pvlib-python.readthedocs.io/en/stable/generated/pvlib.solarposition.get_solarposition.html)

**Comment by jehyunlee** [comment]
Thanks for kind answer. I'll try again. 👍

**Comment by jehyunlee** [comment]
My system is `Ubuntu 18.04` installed on `WSL2` running as a docker container.

**Comment by mikofski** [comment]
I don't believe the version of Ubuntu or WSL will matter, b/c conda installs its own versions of gcc, let me know how it goes, good luck!

**Comment by mikofski** [comment]
@jehyunlee Any update? Are you still having trouble compiling in a fresh conda environment?

**Comment by jehyunlee** [comment]
@mikofski Thanks for your check-up. It works fine on another machine. I still do not have any idea why, however it is clear that there are something wrong on my environment. 👍
